### PR TITLE
⬆️ Update Grocy to v3.2.0

### LINKED ISSUE #282: Allow to set Catalan localization
# Problem/Motivation

One cannot configure Grocy to use the Catalan localization.

## Expected behavior

It is possible to configure Grocy with "culture: ca".

## Actual behavior

It is not possible to configure Grocy with "culture: ca". The UI shows the following error when atemting to save:
```
value must be one of ['cs', 'da', 'de', 'el_GR', 'en', 'en_GB', 'es', 'fi', 'fr', 'he_IL', 'hu', 'it', 'ja', 'ko_KR', 'nl', 'no', 'pl', 'pt_BR', 'pt_PT', 'ru', 'sk_SK', 'sv_SE', 'ta', 'tr', 'zh_CN', 'zh_TW'].
```

## Steps to reproduce

1. Install the addon.
2. Try to configure it with "culture: ca". 

## Proposed changes

Add "ca" in the cultures list in grocy/config.yaml.

### PR DESCRIPTION
**Pull request by malcp**
# Proposed Changes

Bumped Grocy version to v3.2.0. The addon was tested following the "Local Add-on Testing" in https://developers.home-assistant.io/docs/add-ons/testing/

## Related Issues

- https://github.com/hassio-addons/addon-grocy/pull/280
- closes #282

### CODE REVIEW

**Comment by oli-f** [comment]
I just noticed that the [fix_braindamage.patch](https://github.com/hassio-addons/addon-grocy/blob/main/grocy/rootfs/patches/fix_braindamage.patch) patch fails due to [this](https://github.com/grocy/grocy/commit/51fdefaede79ab61be8a250f5c7b42b2e2a361ba) commit.

I have adapted and tested the patch:
```diff
diff --git a/views/layout/default.blade.php b/views/layout/default.blade.php
index 4eb3fb8d..d4e5e007 100644
--- a/views/layout/default.blade.php
+++ b/views/layout/default.blade.php
@@ -88,6 +88,10 @@
 		Grocy.Mode = '{{ GROCY_MODE }}';
 		Grocy.BaseUrl = '{{ $U('/') }}';
 		Grocy.CurrentUrlRelative = "/" + window.location.href.split('?')[0].replace(Grocy.BaseUrl, "");
+		if(Grocy.BaseUrl.indexOf('http') != 0 || Grocy.BaseUrl.indexOf('hassio_ingress') >= 0) {
+			Grocy.BaseUrl = window.location.origin + '{{ $U('/') }}';
+			Grocy.CurrentUrlRelative = "/" + window.location.pathname.replace(Grocy.BaseUrl, "");
+		};
 		Grocy.ActiveNav = '@yield('activeNav', '')';
 		Grocy.Currency = '{{ GROCY_CURRENCY }}';
 		Grocy.CalendarFirstDayOfWeek = '{{ GROCY_CALENDAR_FIRST_DAY_OF_WEEK }}';
```

**Comment by jlsjonas** [comment]
Is anything blocking this (besides @frenck's time)?

**Comment by frenck** [comment]
@jlsjonas working on the add-on as we speak...

**Comment by frenck** [comment]
This PR does contain multiple things that don't belong in a single PR. So it won't be merged though.

**Comment by jlsjonas** [comment]
Apart from the unfortunate commit message naming the diff feels quite in scope? (bumping grocy & fixing related items + patch-bumping used php8 modules as part of a general version bump feel quite related)

**Comment by jlsjonas** [comment]
Agreed and misconception on my end, I thought the patch fix was due to the version bump.
I do fail to see the new feature though (ca language? Didn't that come from the update?)

**Comment by malcp** [comment]
Sorry if I mixed things up. These were my reasons:
- The dependency bumps were required by Grocy v3.2.0, otherwise it wouldn't work.
- Catalan language was introduced in Grocy v3.2.0, so I thought it would make sense to enable it in this PR.
- There is no bug fix. Updating fix_braindamage.patch is needed because Grocy's codebase changed. Failing to do so would cause a regression.

**Comment by malcp** [comment]
I'm happy to modify/split this PR if that would unblock it from getting merged.

**Comment by frenck** [comment]
I've rebased the PR and pulled out the dependency upgrades that way.

Let's go ahead and merge the rest in one. In general, it's nice for someone to read "Catalan" was added as a language (or other changes that are made). Those will be hidden in a single upgrade message (which is not transparent).

**Comment by frenck** [comment]
(close/re-open was to re-trigger CI, GitHub was having some hickups earlier today)

**Comment by malcp** [comment]
> I've rebased the PR and pulled out the dependency upgrades that way.
> 
> Let's go ahead and merge the rest in one. In general, it's nice for someone to read "Catalan" was added as a language (or other changes that are made). Those will be hidden in a single upgrade message (which is not transparent).

Great! And fair point, I'll keep this in mind for next time.

**Pull request merged**
