### PR TITLE
⬆️ Upgrades Grocy to 3.0.1

### PR DESCRIPTION
**Pull request by synth3tk**
# Proposed Changes

Updates Grocy to latest version 3.0.1. Including only warnings and breaking changes here. Full changelogs can be found below.

> ⚠️ The major version bump is due to breaking API changes, please see below if you use the API

> ⚠️⚠️ SQLite >= 3.9.0 (was released in late 2015) is required
>
> [Here](https://github.com/grocy/grocy/issues/1209#issuecomment-749760765) is a workaround if you still run a SQLite version >= 3.8.3 < 3.9.0
>
> _PHP 7.2 with SQLite 3.8.3 was the formerly in [README mentioned](https://github.com/grocy/grocy#how-to-install) minimum runtime requirement, any future release will only be tested against a reasonable recent runtime (currently PHP 7.4 with SQLite 3.27.2) - supporting those (very) old runtime stuff is too time consuming..._

> ❗ If some pages/tables doesn't load at all, please check that your `/data/config.php` setting `CURRENCY` is a valid ISO 4217 currency code - that's most probably the issue then.

### API improvements/fixes
- ⚠️ **Breaking changes**:
  - All prices are now related to the products stock quantity unit (instead of the products purchase QU)
  - All (product) amounts are now related to the products stock quantity unit (was related to the products purchase QU for the shopping list before)
  - The product object no longer has a field `barcodes` with a comma separated barcode list, instead barcodes are now stored in a separate table/entity `product_barcodes` (use the existing "Generic entity interactions" endpoints to access them)
  - The endpoint `/objects/{entity}/search` was removed (use the existing `/objects/{entity}` endpoint with the new filter capabilities mentioned below)
  - The output / field names of `ProductDetailsResponse` have slightly changed (endpoint `/stock/products/{productId}`)
  - Endpoint `/stock/volatile`
    - The query parameter `expring_days` was renamed to `due_soon_days`
    - The field `expiring_products` was renamed to `due_products`
    - The field `expired_products` now only contains expired products (so them with `Due date type = Expiration date`)
    - The new field `overdue_products` contains only overdue products (so them with `Due date type = Best before date`)
  - The following endpoints now return all bookings of the transaction (so the response is now an array, was before a single stock booking - and a random one if the transaction affected multiple stock entries)
    - PUT `/stock/entry/{entryId}`
    - POST `/stock/products/{productId}/add`
    - POST `/stock/products/{productId}/consume`
    - POST `/stock/products/{productId}/transfer`
    - POST `/stock/products/{productId}/inventory`
    - POST `/stock/products/{productId}/open`
    - POST `/stock/products/by-barcode/{barcode}/add`
    - POST `/stock/products/by-barcode/{barcode}/consume`
    - POST `/stock/products/by-barcode/{barcode}/transfer`
    - POST `/stock/products/by-barcode/{barcode}/inventory`
    - POST `/stock/products/by-barcode/{barcode}/open`
    - (The response is the same as if you would fetch the stock transaction via `/stock/transactions/{transactionId}`)

https://github.com/grocy/grocy/releases/tag/v3.0.0

https://github.com/grocy/grocy/releases/tag/v3.0.1

## Related Issues

None

### CODE REVIEW

**Comment by synth3tk** [comment]
I'm not sure how to test this but I want to test it before submitting it as ready. Are there instructions somewhere?

**Comment by frenck** [comment]
This cannot be tested, as it is lacking a lot to be able to even build.

Closing this PR.

**Comment by synth3tk** [comment]
I'm pretty confused. What's missing to build it? I simply followed how the previous upgrades were done in this repo.

**Comment by frenck** [comment]
I don't care. You should test what you send in as a PR. Which you clearly didn't, as you would have ended up with a failed build.

**Comment by synth3tk** [comment]
So how do I test it? I mentioned that I don't see instructions how to do that. Anyway, I apologize for wasting your time.

**Comment by frenck** [comment]
See developers guide of Home Assistant on how to develop add-ons.

https://developers.home-assistant.io

**Pull request closed without merging**
