### PR TITLE
Upgrades nginx to 1.16.1-r1 & php7 to 7.3.11-r0

### PR DESCRIPTION
**Pull request by adec**
# Proposed Changes

> Update nginx & php7 dependencies to resolve build issue.

### CODE REVIEW

**Comment by frenck** [comment]
We don't combine multiple package upgrades in a single commit.

Nevertheless, thank you for your contribution. 👍

**Comment by adec** [comment]
Apologies I’m a bit new to this. So to make sure I get it right in future, would it be acceptable to do the php7 packages in 1 commit and the nginx one in another commit; or should each individual package be in a separate one?

**Comment by adec** [comment]
I’ll redo the changes correctly and resubmit the pull request.

**Comment by frenck** [comment]
@adec I have an automated script that handles the upgrades during the maintenance windows. While appreciated, it is really not needed.

**Pull request closed without merging**
