### PR TITLE
Upgrades Grocy to 3.1.2

### PR DESCRIPTION
**Pull request by facastagnini**
# Proposed Changes

https://github.com/grocy/grocy/releases/tag/v3.1.2

Thanks a lot for maintaining this addon @frenck 🚀

### CODE REVIEW

**Comment by frenck** [comment]
Please git rebase this PR onto the latest `main` branch in order to get the builds to pass.

**Comment by facastagnini** [comment]
> Please git rebase this PR onto the latest `main` branch in order to get the builds to pass.

rebased 🚀

**Comment by frenck** [comment]
That is not a rebase... There are now unrelated commits in this PR.

**Comment by facastagnini** [comment]
you are right, the history is all mangled. Replaced with #248

**Comment by frenck** [comment]
?! Why open up a new PR?!

Just fix this one instead?

**Pull request closed without merging**
